import { ChatHistoryMessage, ChatMessage, SearchContext } from "@/types/chat";

/**
 * Builds chronological ChatHistoryMessage array for backend POST /api/chat.
 * Filters out initial bootstrap welcome messages, sending placeholders, error messages, and empty content.
 * Returns at most the 10 most recent eligible entries.
 */
export function buildChatHistory(messages: ChatMessage[]): ChatHistoryMessage[] {
  const eligible = messages.filter((msg) => {
    // Role must be user or assistant
    if (msg.role !== "user" && msg.role !== "assistant") {
      return false;
    }

    // Exclude welcome/bootstrap assistant message not generated by backend
    if (msg.id === "msg-welcome-01") {
      return false;
    }

    // Exclude sending placeholders and error messages
    if (msg.status === "sending" || msg.status === "error") {
      return false;
    }

    // Exclude empty content
    if (!msg.content || !msg.content.trim()) {
      return false;
    }

    return true;
  });

  // Limit to most recent 10 eligible messages in chronological order
  const recent = eligible.slice(-10);

  return recent.map((msg) => ({
    role: msg.role,
    content: msg.content.trim(),
  }));
}

/**
 * Safely normalizes SearchContext returned from backend.
 * Tolerates missing fields or additional unknown fields.
 */
export function normalizeSearchContext(value: unknown): SearchContext | null {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    return null;
  }

  const raw = value as Record<string, unknown>;

  const lastPlaceIds = Array.isArray(raw.last_place_ids)
    ? raw.last_place_ids.filter((id): id is string => typeof id === "string")
    : undefined;

  return {
    last_intent:
      typeof raw.last_intent === "string"
        ? (raw.last_intent as SearchContext["last_intent"])
        : undefined,
    last_search_terms:
      typeof raw.last_search_terms === "string"
        ? raw.last_search_terms
        : raw.last_search_terms === null
        ? null
        : undefined,
    last_location:
      typeof raw.last_location === "string"
        ? raw.last_location
        : raw.last_location === null
        ? null
        : undefined,
    last_search_query:
      typeof raw.last_search_query === "string"
        ? raw.last_search_query
        : raw.last_search_query === null
        ? null
        : undefined,
    last_place_ids: lastPlaceIds,
  };
}
